ballerina-platform/module-ballerinax-googleapis.drive

- drive/modules/listener/watch_schedular.bal
The purpose is to keep the general information outlining overall task progress as info logs and fine-grained informational events that are most useful to debug an application as debug logs.
> Refactor log levels

- drive/client.bal
- drive/modules/listener/util.bal
https://github.com/wso2-enterprise/choreo/issues/4421
https://github.com/wso2-enterprise/choreo/issues/4370
> Update display annotations & remove unused function

- drive/client.bal
- drive/types.bal
Resolves : https://github.com/wso2-enterprise/choreo/issues/4634
> [Google Drive]  Update display annotations

- drive/modules/listener/constants.bal
- drive/modules/listener/watch_schedular.bal
resolves https://github.com/wso2-enterprise/choreo/issues/4817
> Eliminate checkpanic inside watch scheduler

- .github/workflows/ci.yml
- .github/workflows/pull-request.yml
- .github/workflows/release.yml
- Package.md
- README.md
- drive/Package.md
- drive/README.md
- drive/client.bal
- drive/samples/README.md
Refactor remote functions
resolves https://github.com/wso2-enterprise/choreo/issues/4852
Change workflow files
resolves https://github.com/wso2-enterprise/choreo/issues/4853
> Refactor remote functions

- Package.md
- README.md
- drive/Package.md
- drive/README.md
- drive/client.bal
- drive/modules/listener/README.md
- drive/modules/listener/tests/test.bal
- drive/modules/listener/types.bal
- drive/samples/README.md
Refactor remote functions
resolves https://github.com/wso2-enterprise/choreo/issues/4852
> Refactor remote methods

- drive/Ballerina.toml
- drive/client.bal
> The display annotations for Google Drive connector is inconsistent
> $Subject
> Make display annotations for Google Drive connector consistant

- drive/modules/listener/constants.bal
- drive/modules/listener/http_service.bal
- drive/modules/listener/listener.bal
Adding a resource function to the listener so that it will facilitate domain verification 
resolves https://github.com/wso2-enterprise/choreo/issues/5644
> Add resource function to verify domain

- drive/Ballerina.toml
- drive/modules/listener/README.md
- drive/modules/listener/http_service.bal
- drive/modules/listener/listener.bal
- drive/modules/listener/tests/test.bal
- drive/samples/listener_sample/event_on_delete.bal
- drive/samples/listener_sample/event_on_new_file.bal
- drive/samples/listener_sample/event_on_new_folder.bal
- drive/samples/listener_sample/event_on_update_file.bal
- drive/samples/listener_sample/event_on_update_folder.bal
- gradle.properties
Add documentation for domain verification & bump connector version
resolves https://github.com/wso2-enterprise/choreo/issues/5653
> [Google Drive] Add documentation for domain verification 

- drive/Ballerina.toml
- gradle.properties
> [SL Alpha 5]Update versions for the new release

- drive/client.bal
> The display annotations for Google Drive connector is inconsistent
> $Subject
> [SL Beta 1] Make display annotations consistent

- drive/Dependencies.toml
- gradle.properties
**Purpose**
Bump dependency versions to slbeta2
> Bump dependency versions for Ballerina SLBeta2

- drive/modules/listener/constants.bal
- drive/modules/listener/listener.bal
- drive/modules/listener/watch_schedular.bal
Increase wait time after each retry in watch registration
resolves https://github.com/wso2-enterprise/choreo/issues/5886
> [Google Drive] Add retry configurations for watch registration

- drive/Package.md
- drive/README.md
- drive/client.bal
- drive/modules/listener/README.md
- drive/modules/listener/constants.bal
- drive/modules/listener/http_service.bal
- drive/modules/listener/watch_schedular.bal
resolves https://github.com/wso2-enterprise/choreo/issues/6407
> Fix typos in documentation 

- drive/modules/listener/constants.bal
- drive/modules/listener/watch_schedular.bal
Resolves https://github.com/wso2-enterprise/choreo/issues/6097
> [Google Drive] Add error handling for invalid folder or file ID on listener initiation

- drive/Package.md
- drive/README.md
- drive/client.bal
- drive/modules/listener/README.md
- drive/modules/listener/constants.bal
- drive/modules/listener/http_service.bal
- drive/modules/listener/watch_schedular.bal
resolves https://github.com/wso2-enterprise/choreo/issues/6407
> Fix typos in documentation

- drive/modules/listener/constants.bal
- drive/modules/listener/watch_schedular.bal
Resolves https://github.com/wso2-enterprise/choreo/issues/6097
> [Google Drive] add error handling for invalid folder or file ID 

- Package.md
- README.md
- drive/Package.md
- drive/README.md
- drive/client.bal
- drive/constants.bal
- drive/samples/get_file_by_id.bal
- drive/samples/get_file_content_by_id.bal
- drive/tests/test.bal
- drive/types.bal
- drive/utils.bal
resolves https://github.com/wso2-enterprise/choreo/issues/6413
> Add function `GetFileContent` to Google Drive

- Package.md
- README.md
- drive/Package.md
- drive/README.md
- drive/client.bal
- drive/constants.bal
- drive/samples/get_file_by_id.bal
- drive/samples/get_file_content_by_id.bal
- drive/tests/test.bal
- drive/types.bal
- drive/utils.bal
resolves https://github.com/wso2-enterprise/choreo/issues/6413
> Add function GetFileContent to Google Drive

- drive/modules/listener/constants.bal
resolves https://github.com/wso2-enterprise/choreo/issues/6460
>  [Google Drive] Improve the meaningfulness of an error message

- drive/modules/listener/README.md
- drive/samples/listener_sample/event_on_heavy_processing.bal
resolves https://github.com/wso2-enterprise/choreo/issues/6461
> [Google Drive] usage of strands on heavy processing to eliminate timeout issues

- drive/modules/listener/README.md
- drive/samples/listener_sample/event_on_heavy_processing.bal
resolves https://github.com/wso2-enterprise/choreo/issues/6461
> Improve note about usage of strands for heavy processing 

- drive/modules/listener/http_service.bal
- drive/modules/listener/listener.bal
- drive/modules/listener/natives.bal
- drive/modules/listener/types.bal
- drive/modules/listener/util.bal
- drive/modules/listener/watch_schedular.bal
- java-wrapper/src/main/java/org/ballerinalang/googleapis/drive/NativeHttpToGDriveAdaptor.java
- https://github.com/wso2-enterprise/choreo/issues/6866
- Fix concurrency related warning in listener
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
- https://github.com/ballerina-platform/module-ballerinax-slack/pull/42
> Fix listener concurrency warning

- drive/modules/listener/README.md
- drive/modules/listener/tests/test.bal
- drive/samples/listener_sample/event_on_delete.bal
- drive/samples/listener_sample/event_on_new_file.bal
- drive/samples/listener_sample/event_on_new_folder.bal
- drive/samples/listener_sample/event_on_update_file.bal
- drive/samples/listener_sample/event_on_update_folder.bal
fixes https://github.com/wso2-enterprise/choreo/issues/6924
> [Google Drive] fix logging issue & typos

- README.md
- drive/Dependencies.toml
- drive/Package.md
- Bump version to slbeta3 in Dependencies.toml, README.md and Package.md
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
JDK 11
Ballerina SLBeta3-SNAPSHOT
> Bump versions for slbeta3 in master branch

- drive/modules/listener/constants.bal
- drive/samples/copy_file.bal
- drive/samples/create_file.bal
- drive/samples/create_folder.bal
- drive/samples/delete_file_by_id.bal
- drive/samples/download_file.bal
- drive/samples/get_all_files.bal
- drive/samples/get_all_spreadsheets.bal
- drive/samples/get_file_by_id.bal
- drive/samples/get_file_content_by_id.bal
- drive/samples/move_file.bal
- drive/samples/rename_file.bal
- drive/samples/search_files_by_name.bal
- drive/samples/search_google_docs_by_name.bal
- drive/samples/search_google_forms_by_name.bal
- drive/samples/search_google_sheets_by_name.bal
- drive/samples/search_google_slides_by_name.bal
- drive/samples/update_file.bal
- drive/samples/upload_file.bal
- drive/samples/upload_file_using_byte_array.bal
1. Here I have removed the `checkpanic` keyword from all samples. 
2. Fixed a typo in a constant
> Mitigate the usage of checkpanic

- .github/workflows/ci.yml
- .github/workflows/daily-build.yml
- .github/workflows/pull-request.yml
- .github/workflows/release.yml
- README.md
- drive/Dependencies.toml
Related https://github.com/ballerina-platform/ballerina-extended-library/issues/128
- Add slbeta4 migration changes
* Ballerina Version: Ballerina swan lake beta 4
* Operating System: Ubuntu (Linux)
* Java SDK: Java 11
> add beta3 migration changes

- drive/client.bal
Modify icon as per new requirements 
- Removed .svg icon and added .png icon
- Icon size 200 x 200 px 
- Mention the icon in `Ballerina.toml` so that Ballerina central will render the connector icon
Fixes https://github.com/ballerina-platform/ballerina-extended-library/issues/179
- Improved connector icon
Please delete options that are not relevant.
N/A
N/A
> Modify icon path in client.bal

- drive/tests/test.bal
fix unreachable code issue
- fix unreachable code issue
* Ballerina Version: slbeta6
* Operating System: ubuntu
* Java SDK: Java11
> fix unreachable code issue

- drive/samples/copy_file.bal
- drive/samples/create_file.bal
- drive/samples/create_folder.bal
- drive/samples/delete_file_by_id.bal
- drive/samples/download_file.bal
- drive/samples/get_all_files.bal
- drive/samples/get_all_spreadsheets.bal
- drive/samples/get_file_by_id.bal
- drive/samples/get_file_content_by_id.bal
- drive/samples/move_file.bal
- drive/samples/rename_file.bal
- drive/samples/search_files_by_name.bal
- drive/samples/search_google_docs_by_name.bal
- drive/samples/search_google_forms_by_name.bal
- drive/samples/search_google_sheets_by_name.bal
- drive/samples/search_google_slides_by_name.bal
- drive/samples/update_file.bal
- drive/samples/upload_file.bal
- drive/samples/upload_file_using_byte_array.bal
update samples fixing an error that comes when we don't return `error?` in a code block where `check` is used.
- Fix an error that comes when we don't return `error?` in a code block where `check` is used.
* Ballerina Version: Slbeta6
* Operating System: Ubuntu
* Java SDK: Java11
> update samples fixing an error

- drive/Dependencies.toml
- Update Dependencies.toml with latest standard library versions
> Re-generate Dependencies.toml with latest pack

- drive/Ballerina.toml
- drive/Dependencies.toml
- drive/Package.md
- gradle.properties
prepare connector for Swan Lake `2201.0.0` release
> prepare connector for `2201.0.0` release

- drive/Ballerina.toml
- drive/Dependencies.toml
- drive/Package.md
- drive/client.bal
- drive/config-types.bal
- drive/types.bal
Revamp connector 
related [#14865](https://github.com/wso2-enterprise/choreo/issues/14865)
* Ballerina Version: Ballerina 2201.2.0
* Operating System: Ubuntu
* Java SDK: Java 11
> Revamp connector

- drive/client.bal
- drive/config-types.bal
Related https://github.com/wso2-enterprise/choreo/issues/14865
Related https://github.com/wso2-enterprise/choreo/issues/15133
* Ballerina Version: Ballerina 2201.2.0
* Operating System: Ubuntu
* Java SDK: Java 11
> fix #15133

- drive/Dependencies.toml
- drive/client.bal
- drive/config-types.bal
- drive/types.bal
ConnectionConfig record is used from `ballerinax/client.config` module. https://github.com/wso2-enterprise/choreo/issues/14865
> Use client.config module for ConnectionConfig

- .github/workflows/dev-stg-release.yml
- .github/workflows/release.yml
- drive/Ballerina.toml
- drive/Package.md
- drive/types.bal
> Bump bal version to 2201.2.1

- README.md
- drive/Package.md
$Subject
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/474
> Update Slack channel occurrences with Discord

- drive/Ballerina.toml
- drive/Dependencies.toml
- drive/Package.md
$Subject
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/475
> Update to Ballerina version 2201.3.0

- .github/workflows/dev-stg-release.yml
- .github/workflows/release.yml
- ballerina/Ballerina.toml
- ballerina/Package.md
- ballerina/client.bal
- ballerina/utils.bal
$subject. 
Fixes https://github.com/ballerina-platform/ballerina-extended-library/issues/577
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
* Ballerina Version:
* Operating System:
* Java SDK:
> Fix compatibility issues with 2201.8.0

- .github/workflows/release.yml
Related to https://github.com/ballerina-platform/ballerina-extended-library/issues/589
Related Pull Requests (remove if not relevant)
- Pull request 1
- Pull request 2
- One line describing the feature/improvement/fix made by this PR 
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
* Ballerina Version:
* Operating System:
* Java SDK:
> Fix central access token in release workflow

- ballerina/Ballerina.toml
- ballerina/client.bal
- ballerina/tests/README.md
- ballerina/tests/test.bal
- ballerina/types.bal
- ballerina/utils.bal
- examples/export_file_content.bal
- examples/list_changes.bal
This PR introduces support for the following Google Drive v3 API resource endpoints under the `ballerinax/googleapis.drive` module:
- `exportFile` – Export a Google Docs/Sheets/Slides file into a different MIME type (e.g., PDF)
- `getStartPageToken` – Retrieve the current start page token for listing future changes
- `listChanges` – Retrieve a list of changes made to the user's Drive since the provided page token
These additions enhance the Ballerina Google Drive Connector’s functionality by enabling users to track changes in their Drive and export Google-native files to various formats, thus supporting a wider range of automation and backup use cases.
Fixes: # (N/A)
Related Pull Requests:
- N/A
One line release note:
- Add support for Google Drive `v3.changes` API and file export …
> Add 'getStartPageToken' and 'listChanges' APIs
